import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/layout";
import {
  Bars3Icon,
  BellIcon,
  CalendarIcon,
  ChartPieIcon,
  Cog6ToothIcon,
  DocumentDuplicateIcon,
  FolderIcon,
  HomeIcon,
  UsersIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation = [
  { name: 'Dashboard', href: '#', icon: <HomeIcon className="w-5 h-5"/>, current: true },
  { name: 'Team', href: '#', icon:  <HomeIcon className="w-5 h-5"/>, current: false },
  { name: 'Projects', href: '#', icon:  <HomeIcon className="w-5 h-5"/>, current: false },
  { name: 'Calendar', href: '#', icon:  <HomeIcon className="w-5 h-5"/>, current: false },
  { name: 'Documents', href: '#', icon:  <HomeIcon className="w-5 h-5"/>, current: false },
  { name: 'Reports', href: '#', icon:  <HomeIcon className="w-5 h-5"/>, current: false },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout sideMenus={navigation}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
